name: Publish Nuget Release Package

on:
  release:
    types:
      - created

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:        
     
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}      

    #Maybe later we should use the tag name as version number
    - name: Increment patch version
      shell: bash
      run: |
        FILE=./MudBlazor.Extensions/MudBlazor.Extensions.csproj
        CURRENT_VERSION=$(grep -oPm1 "(?<=<PatchVersion>)[^<]+" $FILE)
        NEW_VERSION=$((CURRENT_VERSION + 1))
        sed -i "s/<PatchVersion>$CURRENT_VERSION<\/PatchVersion>/<PatchVersion>$NEW_VERSION<\/PatchVersion>/g" $FILE
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Increment version number" -a           

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - name: Push changes
      run: |
        git tag -fa ${{ steps.extract_branch.outputs.branch }} -m "Force updated tag"
        git push origin :refs/tags/${{ steps.extract_branch.outputs.branch }}
        git push origin HEAD:refs/tags/${{ steps.extract_branch.outputs.branch }}
      
    - name: Checkout code
      uses: actions/checkout@v2      

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'

    - name: Restore dependencies
      run: dotnet restore ./MudBlazor.Extensions/MudBlazor.Extensions.csproj
      
    - name: First Build (ignore errors)
      continue-on-error: true
      run: dotnet build ./MudBlazor.Extensions/MudBlazor.Extensions.csproj --configuration Release --no-restore

    - name: Second Build
      run: dotnet build ./MudBlazor.Extensions/MudBlazor.Extensions.csproj --configuration Release --no-restore      

    - name: Publish Package
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      shell: pwsh
      run: |
        Get-ChildItem -Path MudBlazor.Extensions/bin/Release -Filter *.nupkg | ForEach-Object {
          dotnet nuget push $_.FullName -k $env:NUGET_API_KEY -s https://api.nuget.org/v3/index.json
        }      
